name: 'Deploy website to AWS'
description: ' Deploy a static website via s3'
inputs:
  s3bucket:
    description: 's3 bucket name'
    required: true
  region:
    description: 'aws region'
    required: false
    default: 'us-east-2'
  dist-folder:
    description: 'the folder containing the deployable artifacts'
    required: true
runs:
  using: 'node16'
  main: 'main.js'