name: 'Get & Cache Dependencies'
description: 'Get the Dependencies (via npm) and cache them'
inputs:
  caching: 
    description: 'turn on or off caching for the dependencies'
    required: true
    default: 'true'
runs: 
  using: 'composite'
  steps:
  - name: echo Caching Status
    if: inputs.caching != 'true'
    run: echo 'Caching is turned off'
    shell: bash
  - name: Cache dependencies
    if: inputs.caching.value == 'true'
    id: cache
    uses: actions/cache@v4
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
    run: npm ci
    shell: bash